### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by martonteker** [average-js-enjoyers/average-js-webshop#114]
- [ ] As a **user**, I want to **view and update my personal details**, including name, billing & shipping addresses, and photo upload for **personal account management**.
- [ ] As a **user**, I want to view my **purchase history** to **keep track of my transactions**.
- [x] As a **user**, I want a **change password option** for **maintaining account security**.
