### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by szabogaliakos** [average-js-enjoyers/average-js-webshop#48]
# Definition of Done ✅

- [ ] Displays aggregate business and performance information for Business Administrators.
  - [ ] Current / last month
  - [ ] Number of active users
  - [ ] Numer of orders
  - [ ] Total sales revenue
  - [ ] Average sales order value
  - [ ] Median sale order value
  - [ ] Pertenctile distribution of sales order value (left / right skew) - OPTIONAL
  - [ ] Changes in percentages for above indicators
- [ ] Query indicator on specific date interval for above indicators
  - [ ] With calendar, custom interval
  - [ ] With presets (last year, all time, past 3 months)
- [ ] Chart with indicator changes over time
- [ ] User device indicator (Categorize users by device type etc. iPhone, desktop, tablet)
- [ ] View all pending new orders (also send email to subscribed admin addresses)

# Resources ⚒️

https://github.com/BootstrapDash/star-admin2-free-admin-template
