### ISSUE TITLE
Inventory Management

### ISSUE THREAD

**Issue by szabogaliakos** [average-js-enjoyers/average-js-webshop#50]
# Definition of Done ✅

- [ ] Separate screen with Product Items list (qty can be managed with a field)
- [ ] Display attributes
  - [ ] Product_item_id (readOnly)
  - [ ] Product Name
  - [ ] SKU / Product Number
  - [ ] Quantity
  - [ ] Unit (sales) Price
  - [ ] Last purchase price
- [ ] List can be sorted and filtered similar to Product Screen
- [ ] For mass stock update admin can add New Delivery (delivery note)
- [ ] Filter products
- [ ] ~~Inventory Change Log (with option for discarding changes)~~
- [ ] ~~Add New Delivery Screen with general info and product item list~~

# ENDPOINT 🌐

## Product Items List
```
GET api/admin/inventory/items - List all product items with their attributes. Supports sorting and filtering.
```

## View Product Item
```
GET api/admin/inventory/item/{productItemId} - Get details of a specific product item.
```

## Update Quantity of a Product Item
```
PUT api/admin/inventory/item/{productItemId}/update-qty - Update the quantity of a specific product item.
```

## Mass Stock Update (New Delivery)
```
POST api/admin/inventory/delivery - Add a new delivery to update stock in bulk.
```

## Filter Product Items
```
GET api/admin/inventory/items/filter - Filter product items based on various criteria like Product Name, SKU, etc.
```

## Inventory Change Log
```
GET api/admin/inventory/change-log - View the inventory change log.
POST api/admin/inventory/change-log/discard - Discard changes from the inventory change log.
```

## New Delivery Screen Data
```
GET api/admin/inventory/delivery/info - Get general info needed for the New Delivery screen.
GET api/admin/inventory/delivery/products - Get product item list for New Delivery.
```
